common: &common
  adapter: mysql2
  database: <%= ENV['DATABASE_NAME'] %>
  encoding: utf8
  host: <%= ENV['DATABASE_HOST'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5
  reconnect: false
  timeout: 5000
  username: <%= ENV['DATABASE_USERNAME'] %>

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
  