common: &common
  adapter: mysql2
  database: listy_development
  pool: 5
  timeout: 5000
  username: root
  password: 123qwe

development:
  <<: *common

test:
  <<: *common
  database: listy_test

production:
  <<: *common
  database: listy_production
