llist = Llist.create(name: 'test')
llist.litems.create(name: 'breakfast', text: 'the best meal of the day')
llist.litems.create(name: 'second breakfast')
llist.litems.create(name: 'lunch')
llist.litems.create(name: 'dinner')